import SinglePost from "@/components/Post/SinglePost";
import { getPostsForTopPage } from "@/lib/notionAPI";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [
      {
        params: {
          page: "1",
        },
        params: {
          page: "2",
        },
      },
    ],
    fallback: "blocking",
  };
};

// SSG:ビルド時にあらかじめデータを取得しておく
export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage(4);
  return {
    props: {
      fourPosts,
    },
    // ISR:60秒ごとにデータを更新する
    revalidate: 60,
  };
};

const BlogPageList = ({ fourPosts }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          NotionBlog 🚀
        </h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {fourPosts.map((post) => {
            return (
              <div>
                <SinglePost
                  title={post.title}
                  description={post.description}
                  date={post.date}
                  tags={post.tags}
                  slug={post.slug}
                  isPaginationPage={true}
                />
              </div>
            );
          })}
        </section>
      </main>
    </div>
  );
};

export default BlogPageList;
