import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

// SSG:ビルド時にあらかじめデータを取得しておく
export const getStaticProps = async () => {
  const allPosts= await getAllPosts();
  return {
    props: {
      allPosts,
    },
    // ISR:60秒ごとにデータを更新する
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-10xl font-bold underline">Hello world!</h1>
    </>
  );
}
