import SinglePost from "@/components/Post/SinglePost";
import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

// SSG:ビルド時にあらかじめデータを取得しておく
export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  return {
    props: {
      allPosts,
    },
    // ISR:60秒ごとにデータを更新する
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          NotionBlog 🚀
        </h1>
        {allPosts.map((post) => {
          return (
            <div className="mx-4">
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tag={post.tag}
                slug={post.slug}
              />
            </div>
          );
        })}
      </main>
    </div>
  );
}
